developing
Naroru/GitHubTest pull request #1
Opened 2023-12-29 11:49 UTC by Naroru

I added new features

2023-12-29 14:38 UTC, nerevar51 commented
> I added new features

Hello

2023-12-29 14:42 UTC, nerevar51 requested changes

2023-12-29 14:42 UTC, nerevar51 commented on src/main/java/Main.java
> +//developing
You should change it to Developing 2

2023-12-29 14:42 UTC, nerevar51 commented on src/main/resources/someFile.txt
> +developing
here change to developing 3

2023-12-30 07:12 UTC, Naroru commented on src/main/java/Main.java
> +//developing 2
```suggestion
//developing 3
```
sorry, it should be developing 3 also

2023-12-30 07:15 UTC, nerevar51 approved these changes

2023-12-30 07:16 UTC, merged